[package]
name = "typst-wasm-macros"
edition = "2021"
version.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
venial = { workspace = true }
